### ISSUE TITLE
ERROR Charm feature requirements cannot be met

### ISSUE THREAD

**Issue by hazem-soussi** [canonical/juju-dashboard-charm#30]
root@hazem-pfe:~# juju status
Model       Controller           Cloud/Region         Version  SLA          Timestamp
controller  localhost-localhost  localhost/localhost  3.1.5    unsupported  14:09:06Z

App         Version  Status  Scale  Charm            Channel     Rev  Exposed  Message
controller           active      1  juju-controller  3.1/stable   14  no

Unit           Workload  Agent  Machine  Public address  Ports  Message
controller/0*  active    idle   0        10.217.74.97

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.217.74.97  juju-4553c3-0  ubuntu@22.04      Running
root@hazem-pfe:~# juju deploy juju-dashboard-k8s dashboard

Located charm "juju-dashboard-k8s" in charm-hub, revision 8
Deploying "dashboard" from charm-hub charm "juju-dashboard-k8s", revision 8 in channel stable on ubuntu@22.04/stable
ERROR Charm feature requirements cannot be met:
  - charm requires feature "k8s-api" but model does not support it

Feature descriptions:
  - "k8s-api": the Kubernetes API lets charms query and manipulate the state of API objects in a Kubernetes cluster

For additional

**Comment by barrettj12** [comment]
You're getting this because you're trying to deploy a K8s charm on a LXD controller. You should deploy [`juju-dashboard`](https://charmhub.io/juju-dashboard) instead of `juju-dashboard-k8s`.
